/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Source Highlight
 #	author : miyako
 #	2013/08/03
 #
 # --------------------------------------------------------------------------------*/


void _getDefaultLangFolderPath(C_TEXT *p);

// --- source-highlight
void CODE_HIGHLIGHT(sLONG_PTR *pResult, PackagePtr pParams);

// --- preferences
void CODE_GET_LANGUAGE_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void CODE_Set_language_folder(sLONG_PTR *pResult, PackagePtr pParams);
void CODE_Get_language_folder(sLONG_PTR *pResult, PackagePtr pParams);
